# Generated by Django 2.2.2 on 2019-12-10 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cook', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('number_of_ingredients', models.IntegerField(blank=True)),
                ('ingredient_amount', models.DecimalField(decimal_places=2, max_digits=2)),
                ('instruction', models.TextField(max_length=1000, verbose_name='Place instruction here...')),
                ('prep_time', models.IntegerField()),
                ('cooking_time', models.IntegerField()),
                ('serves_amount', models.IntegerField()),
                ('serves_ppl', models.IntegerField()),
                ('published_date', models.DateTimeField(verbose_name='Recipe made:')),
            ],
        ),
    ]
