# Generated by Django 2.2.2 on 2019-12-11 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipedetails',
            options={'verbose_name_plural': 'RecipeDetails'},
        ),
        migrations.RenameField(
            model_name='recipedetails',
            old_name='cook',
            new_name='Dish',
        ),
        migrations.RenameField(
            model_name='recipedetails',
            old_name='title',
            new_name='Dish_Author',
        ),
    ]
