# Generated by Django 2.2.2 on 2019-12-17 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20191211_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipedetails',
            old_name='Dish_Author',
            new_name='Cook',
        ),
    ]
