# Generated by Django 3.0 on 2019-12-17 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_auto_20191217_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipedetails',
            name='Cook',
        ),
        migrations.RemoveField(
            model_name='recipedetails',
            name='Dish',
        ),
        migrations.RemoveField(
            model_name='recipedetails',
            name='cooking_time',
        ),
        migrations.RemoveField(
            model_name='recipedetails',
            name='description',
        ),
        migrations.RemoveField(
            model_name='recipedetails',
            name='ingredient_amount',
        ),
        migrations.RemoveField(
            model_name='recipedetails',
            name='instruction',
        ),
        migrations.RemoveField(
            model_name='recipedetails',
            name='number_of_ingredients',
        ),
        migrations.RemoveField(
            model_name='recipedetails',
            name='prep_time',
        ),
        migrations.RemoveField(
            model_name='recipedetails',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='recipedetails',
            name='serves_amount',
        ),
        migrations.RemoveField(
            model_name='recipedetails',
            name='serves_ppl',
        ),
    ]
