# Generated by Django 3.0 on 2020-01-07 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_auto_20191217_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipedetails',
            name='cooking_time',
        ),
        migrations.RemoveField(
            model_name='recipedetails',
            name='description',
        ),
        migrations.RemoveField(
            model_name='recipedetails',
            name='ingredient_amount',
        ),
        migrations.RemoveField(
            model_name='recipedetails',
            name='instruction',
        ),
        migrations.RemoveField(
            model_name='recipedetails',
            name='prep_time',
        ),
        migrations.RemoveField(
            model_name='recipedetails',
            name='serves_amount',
        ),
        migrations.RemoveField(
            model_name='recipedetails',
            name='serves_ppl',
        ),
    ]
