# Generated by Django 3.0 on 2020-01-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_auto_20200107_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipedetails',
            name='cooking_time',
            field=models.IntegerField(default=0),
        ),
    ]
