# Generated by Django 3.0 on 2020-01-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_recipedetails_cooking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipedetails',
            name='number_of_ingredients',
            field=models.IntegerField(default=0),
        ),
    ]
