# Generated by Django 3.0 on 2020-02-04 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0009_auto_20200204_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipedetails',
            name='instruction',
            field=models.TextField(default='Place instruction here...', max_length=5000),
        ),
    ]
