# Generated by Django 3.0 on 2020-02-16 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0011_auto_20200215_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipedetails',
            name='photo_1',
            field=models.ImageField(blank=True, upload_to='photos/food/'),
        ),
        migrations.AlterField(
            model_name='recipedetails',
            name='photo_2',
            field=models.ImageField(blank=True, upload_to='photos/food/'),
        ),
        migrations.AlterField(
            model_name='recipedetails',
            name='photo_3',
            field=models.ImageField(blank=True, upload_to='photos/food/'),
        ),
        migrations.AlterField(
            model_name='recipedetails',
            name='photo_4',
            field=models.ImageField(blank=True, upload_to='photos/food/'),
        ),
        migrations.AlterField(
            model_name='recipedetails',
            name='photo_5',
            field=models.ImageField(blank=True, upload_to='photos/food/'),
        ),
        migrations.AlterField(
            model_name='recipedetails',
            name='photo_6',
            field=models.ImageField(blank=True, upload_to='photos/food/'),
        ),
    ]
