# Generated by Django 3.0 on 2020-02-22 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0013_auto_20200219_1538'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipedetails',
            options={},
        ),
    ]
