# Generated by Django 3.0 on 2020-02-22 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0014_auto_20200222_1122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipedetails',
            options={'verbose_name_plural': 'Recipe Details'},
        ),
    ]
