# Generated by Django 3.0 on 2020-04-26 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0016_auto_20200424_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipedetails',
            name='photo_1',
        ),
        migrations.RemoveField(
            model_name='recipedetails',
            name='photo_2',
        ),
        migrations.RemoveField(
            model_name='recipedetails',
            name='photo_3',
        ),
        migrations.RemoveField(
            model_name='recipedetails',
            name='photo_4',
        ),
        migrations.RemoveField(
            model_name='recipedetails',
            name='photo_5',
        ),
        migrations.RemoveField(
            model_name='recipedetails',
            name='photo_6',
        ),
    ]
